# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push request
# events but only for the master branch
# triggers everyday at 7:00AM CST
on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sign_in"
  sign_in:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup python 3.x environment and requests package
    - name: Set python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade requests
    
    # Run auto sign in script of hao4k.cn
    - name: Hao4k auto sign in
      env:
        HAO4K_USERNAME: ${{ secrets.HAO4K_USERNAME }}
        HAO4K_PASSWORD: ${{ secrets.HAO4K_PASSWORD }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: python autosignin.py
        
